name: 'Get service principal'
description: 'Retrieve service principal for given env'
author: 'notanops'

inputs:
  stack-name:
    description: 'Name of the stack'
    required: false
outputs:
  service-principal:
    description: 'Service principal to use'
    value: ${{ steps.extract_service_principal.outputs.service-principal}}
runs:
  using: composite
  steps:
  - name: Make executable
    run: chmod +x main
    shell: bash
  - name: Move binary to project folder
    run: mv main project/
    shell: bash
  - id: extract-service-principal
    name: Run
    run: ./project/main
    shell: bash
    env:
      stack-name: ${{ inputs.stack-name }}
