name: 'Get service principal'
description: 'Retrieve service principal for given env'
author: 'notanops'

inputs:
  stack-name:
    description: 'Name of the stack'
    required: false
outputs:
  service-principal:
    description: 'Service principal to use'
    value: ${{ steps.extract_service_principal.outputs.service-principal}}
runs:
  using: composite
  steps:
  - name: Checkout Pulumi project
    uses: actions/checkout@v3
    with:
      path: project
  - uses: suisei-cn/actions-download-file@v1.3.0
    name: Download the file
    with:
      url: "https://github.com/notanops/GetServicePrincipal/raw/main/getserviceprincipal"
      target: ./project
  - name: What's inside
    run: ls -a project
    shell: bash
  - name: Make executable
    run: chmod +x getserviceprincipal
    shell: bash
  - name: Run getServicePrincipal
    run: ./getserviceprincipal
    shell: bash
    env:
      stack-name: ${{ inputs.stack-name }}
